source 'https://rubygems.org'


gem 'rails', '~> 6'
gem 'sqlite3'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'

gem 'jquery-rails'
gem 'turbolinks'
gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'spring',        group: :development

path './components' do
  gem 'obviously-invalid-dependencies'
  gem 'obviously-valid-dependencies'
  gem 'invalid-sub-dependencies'
end

group :development, :test do
  gem 'rspec', '~> 3.1'
  gem 'capybara', '~> 2.1'
end
