source 'https://rubygems.org'


gem 'rails', '4.1.8'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'spring',        group: :development

path './components' do
  gem 'obviously-invalid-dependencies'
  gem 'obviously-valid-dependencies'
  gem 'invalid-sub-dependencies'
end

group :development, :test do
  gem 'rspec', '~> 3.1'
  gem 'capybara-webkit', '~> 1.3.1'
  gem 'capybara', '~> 2.1'
end
